# Generated by Django 2.2.5 on 2021-05-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='customer',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='website.Customer'),
        ),
    ]
