# Generated by Django 2.2.5 on 2021-05-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_mail_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='image',
        ),
        migrations.AlterField(
            model_name='mail',
            name='customer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Customer'),
        ),
    ]
