# Generated by Django 2.2.5 on 2021-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210518_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
